source 'https://rubygems.org'

gem 'chefspec'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'rspec-support'
gem 'chef', '~> 11.16.0'
gem 'foodcritic', '>=3.0.0'
gem 'daptiv-foodcritic-rules'
gem 'tailor'
gem 'log_switch', '~> 0.4.0' # constrain tailor dependency
gem 'rake'
gem 'berkshelf'
gem 'minitest-chef-handler'
gem 'daptiv-chef-ci', '>= 0.0.6'
