name              'wix'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures Windows Installer XML toolset (WiX)'
version           '6.0.10'
source_url        'https://github.com/sous-chefs/wix'
issues_url        'https://github.com/sous-chefs/wix/issues'
chef_version      '>= 15.0'

supports 'windows'
